// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPnll5Sz-RpgE5-j97gNkr3xPyP-V4Syc',
    appId: '1:249380649381:web:2e64daa11a234a5fa7904c',
    messagingSenderId: '249380649381',
    projectId: 'course-application-official',
    authDomain: 'course-application-official.firebaseapp.com',
    storageBucket: 'course-application-official.firebasestorage.app',
    measurementId: 'G-PLFRGWGC0Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5vqjhdcVMpdm4D-6Rl4oo_5yg_LrMPcw',
    appId: '1:249380649381:android:8f711ad6c719acbaa7904c',
    messagingSenderId: '249380649381',
    projectId: 'course-application-official',
    storageBucket: 'course-application-official.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5kAt64xE71wW0RnwhGUCrBf1HyfumL5Q',
    appId: '1:249380649381:ios:ef8f9e11f20737d6a7904c',
    messagingSenderId: '249380649381',
    projectId: 'course-application-official',
    storageBucket: 'course-application-official.firebasestorage.app',
    androidClientId: '249380649381-3qpllq64v8jbhnasau7ibljad727jgbj.apps.googleusercontent.com',
    iosClientId: '249380649381-t0hculo8efp7ifm812ar7idh7gvjdhm0.apps.googleusercontent.com',
    iosBundleId: 'com.example.courseApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5kAt64xE71wW0RnwhGUCrBf1HyfumL5Q',
    appId: '1:249380649381:ios:ef8f9e11f20737d6a7904c',
    messagingSenderId: '249380649381',
    projectId: 'course-application-official',
    storageBucket: 'course-application-official.firebasestorage.app',
    androidClientId: '249380649381-3qpllq64v8jbhnasau7ibljad727jgbj.apps.googleusercontent.com',
    iosClientId: '249380649381-t0hculo8efp7ifm812ar7idh7gvjdhm0.apps.googleusercontent.com',
    iosBundleId: 'com.example.courseApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPnll5Sz-RpgE5-j97gNkr3xPyP-V4Syc',
    appId: '1:249380649381:web:ab7dca2143d08b27a7904c',
    messagingSenderId: '249380649381',
    projectId: 'course-application-official',
    authDomain: 'course-application-official.firebaseapp.com',
    storageBucket: 'course-application-official.firebasestorage.app',
    measurementId: 'G-YNB1TFQYZ4',
  );
}
