// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKtNktozuuMP0u4cIbJKftUzAudw2utE8',
    appId: '1:227776801675:web:9b3c9df33b10c4087d9d8e',
    messagingSenderId: '227776801675',
    projectId: 'course-application-1',
    authDomain: 'course-application-1.firebaseapp.com',
    storageBucket: 'course-application-1.firebasestorage.app',
    measurementId: 'G-JKP1ZCCE17',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiQkjwY-IBWGxkLVD-mUTSloe6RFCvBpM',
    appId: '1:227776801675:android:6ea6d5862f13d32d7d9d8e',
    messagingSenderId: '227776801675',
    projectId: 'course-application-1',
    storageBucket: 'course-application-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJ9cKZeOljszMOScjOzVpImvaxKwp-PcQ',
    appId: '1:227776801675:ios:d6c683acb6a92fdf7d9d8e',
    messagingSenderId: '227776801675',
    projectId: 'course-application-1',
    storageBucket: 'course-application-1.firebasestorage.app',
    iosBundleId: 'com.example.courseApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJ9cKZeOljszMOScjOzVpImvaxKwp-PcQ',
    appId: '1:227776801675:ios:d6c683acb6a92fdf7d9d8e',
    messagingSenderId: '227776801675',
    projectId: 'course-application-1',
    storageBucket: 'course-application-1.firebasestorage.app',
    iosBundleId: 'com.example.courseApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKtNktozuuMP0u4cIbJKftUzAudw2utE8',
    appId: '1:227776801675:web:6d629f653beb9f797d9d8e',
    messagingSenderId: '227776801675',
    projectId: 'course-application-1',
    authDomain: 'course-application-1.firebaseapp.com',
    storageBucket: 'course-application-1.firebasestorage.app',
    measurementId: 'G-JYJHL7HRWV',
  );
}
